.TH LACKY 1 "October 2012" lackey
.SH NAME
lackey \- curses calendar program
.SH SYNOPSIS
.B lackey\fR [\fIOPTION\fR..]
.SH DESCRIPTION
lackey is a curses calendar program.
.SH OPTIONS
.TP
todo
.SH CONFIGURATION
.TP
todo
.SH FILES
.TP
todo
.SH SEE ALSO
.BR date (1),
.BR cal (1),
.BR cron (1),
.BR at (1),
.BR remind (1),
.BR calcurse (1)
.SH BUGS
Many
